src/wlserver.c
Tested in nested session: allows to kill the process with `Ctrl+C` or kill signal.
=> feat: add signal handlers

LICENSE
The project was licensed under BSD-2-Clause. Add this information back again.
=> docs: add back license file

meson.build
In order to launch the binary with for example Mesa being installed not into
the regular /usr prefix but into something like /opt the binary needs to be
launched from the install directory and not only directly from the build
directory.
So actually do install the executable.
=> build: do install executable

meson.build, src/rendervulkan.cpp, src/shaderbuild.sh
file.
This removes the xxd dependency.
=> Use build in glslangValidator functionally to generate shader include

src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/wlserver.c, src/wlserver.h
The long-term goal is to make cursor painting independent of X11 protocol.
Larger objectives here:
* Introduce MouseCursor class, better encapsulation.
* No round trip through XWayland for getting cursor position, instead just get it from global variable.
* Introduce support for relative pointer and pointer constraints protocol extensions. Fixes #19.
* Unify pointer movement code paths in drm and nested mode, simplifies logic.
Note: To get it to build I needed to add the protocol directory to wlroots top-level meson.build file. I.e.: `wlr_inc = include_directories('.', 'include', 'protocol')`. Otherwise the pointer-constraints-unstable-v1-protocol.h header file is not found. That probably comes from the static linkage.
=> Pointer and cursor improvements

src/drm.cpp, src/drm.hpp, src/main.cpp
When trying the layering I first failed on an assert. That's the second patch.
Then there was a second problem that as soon as I started a game (CS GO) the screen became black. I noticed that if I reset all values of layers that were used in the past but not anymore the game was shown after a certain amount of time.
The reason: as soon as the mouse cursor and the info message in right lower corner was hidden it showed. The cursor or the info message were on a second layer. Whenever there are more than one layer the layer below becomes black. This could be a bug in libliftoff or the kernel driver (tested with RX 5700 XT).
Resetting all values for now is part of the first patch, which does also overall tidy up the loop a bit and adds some verbose debug statements for the loop that can be …
=> Clean up layering loop

src/steamcompmgr.cpp
win objects are allocated with `new`, so they need to be de-allocated
with `delete` instead of `free`.
==589398==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x61200017f140
(EE) failed to read Wayland events: Broken pipe
X connection to :1 broken (explicit kill or server shutdown).
#0 0x7f5468ae4720 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:122
#1 0x559820f5c9a0 in finish_destroy_win ../src/steamcompmgr.cpp:1743
#2 0x559820f5ca6d in destroy_win ../src/steamcompmgr.cpp:1759
#3 0x559820f6163e in steamcompmgr_main ../src/steamcompmgr.cpp:2288
#4 0x559820f8e977 in steamCompMgrThreadRun() ../src/main.cpp:121
#5 0x559820f8e3e9 in void std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) …
=> Fix alloc-dealloc-mismatch for win objects

src/wlserver.cpp
wlr_texture_to_dmabuf involves issuing EGL commands to get a DMA-BUF out
of an EGLImage.
When the client submits a DMA-BUF via the linux-dmabuf protocol, there's
no need to go through EGL. We can directly import the client's DMA-BUF
into Vulkan.
The old code is still retained as a fallback in case the client uses
wl_drm (old Xwayland) or wl_shm. Removing it would involve creating a
Vulkan-based wlr_renderer.
References: https://github.com/Plagman/gamescope/issues/16
=> Get DMA-BUF from wlr_buffer if possible

src/drm.cpp, src/drm.hpp, src/main.cpp, src/main.hpp, src/rendervulkan.cpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/wlserver.cpp
This is a re-do of https://github.com/Plagman/gamescope/pull/48 but with an incremental approach.
Should fix https://github.com/Plagman/gamescope/issues/13
=> Hold client buffers, version 2

src/rendervulkan.cpp
We don't know whether clients create scanout-able DMA-BUFs.
Depends on https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4885
Closes: https://github.com/Plagman/gamescope/issues/40
=> Don't use VK_STRUCTURE_TYPE_WSI_IMAGE_CREATE_INFO_MESA for imported DMA-BUFs

src/steamcompmgr.cpp
Hitting this one now:
```
=================================================================
==112992==ERROR: AddressSanitizer: heap-use-after-free on address 0x618000019cb0 at pc 0x7ffa5a1270a6 bp 0x7ffa4217b890 sp 0x7ffa4217b038
WRITE of size 16 at 0x618000019cb0 thread T20
#0 0x7ffa5a1270a5 in __interceptor_clock_gettime /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:2173
#1 0x5589cd94fb22 in wlr_seat_keyboard_notify_key ../subprojects/wlroots/types/seat/wlr_seat_keyboard.c:336
#2 0x5589cd8690f1 in wlserver_key(unsigned int, bool, unsigned int) ../src/wlserver.cpp:568
#3 0x5589cd88b1d5 in inputSDLThreadRun() ../src/inputsdl.cpp:414
#4 0x5589cd85c7b3 in void std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) …
```
=> Fix segfault on exit

src/steamcompmgr.cpp
``gettimeofday`` is expensive and suffers from NTP drift which means we could miss vblank on time updates.
=> Eliminate usage of `gettimeofday`

src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/vblankmanager.cpp
- Encode vblank time in client message.
- Eliminate mutex for last vblank.
- Keep everything on the same timescale.
- Avoid using floats here when we can just use integer maths.
- Add demarcations.
- Misc. cleanup.
=> Encode vblank time in message and vblankmanager cleanup

meson.build, src/steamcompmgr.cpp
- Add missing header for non-glibc systems
- Add xfixes dependency, used directly by gamescope
- Drop pixman, libinput dependencies, already pulled via wlroots
=> Minor fixes

meson.build
Fixes #22:
- after 5ab3129d8e7d system wlroots should be safe to use
- prefer bundled copies to avoid bustage on package upgrades
More concisely it can be:
```meson
project(
'gamescope',
['c','cpp'],
meson_version: '>=0.54.0',
default_options: [
'warning_level=2',
'default_library=static',
'examples=false',
],
)
....
wlroots_dep = dependency('wlroots', version: '>= 0.11.0', fallback: ['wlroots', 'wlroots'])
liftoff_dep = dependency('liftoff', fallback: ['libliftoff', 'liftoff'])
```
=> Fallback to system wlroots/liftoff when subprojects/ is empty

src/steamcompmgr.cpp, src/steamcompmgr.hpp
Regressed by #28 (f7d815a2037e), so CC @subdiff. From Clang 11 [build log](https://github.com/Plagman/gamescope/files/5419260/gamescope-3.7.6.log):
```c
In file included from ../src/steamcompmgr.cpp:74:
src/steamcompmgr.hpp:75:7: warning: private field 'm_hasPlane' is not used [-Wunused-private-field]
bool m_hasPlane;
^
```
For parity with GCC 11 build which is warning-free. Also, not related to b84750e77576 i.e., dropping `warning_level=2` doesn't silence `-Wunused-private-field`.
=> Fix -Wunused-private-field reported by Clang

src/drm.cpp, src/drm.hpp, src/steamcompmgr.cpp
This fixes black screens when using libliftoff. The main culprit was that the `ALLOW_MODESET` flag wasn't passed during test-only commits. Some refactoring is also included.
In my testing, libliftoff was able to use two planes at the same time without composition (when showing a Steam notification for instance).
Closes: https://github.com/Plagman/gamescope/issues/41
=> Get libliftoff to work consistently

src/drm.cpp, src/drm.hpp, src/rendervulkan.cpp, src/rendervulkan.hpp, src/steamcompmgr.cpp
This makes it so the buffer for the cursor can pass amdgpu's size checks.
Tested with:
```
build/gamescope -e -l -d -w 1920 -h 1080 -- steam -tenfoot -steamos
```
(-w and -h are necessary to remove any scaling because the cursor plane can't be used together with primary plane scaling.)
Then check that the cursor plane is used with `drm_info`.
~~This is not ready to be merged because amdgpu prints some errors, oops and the cursor isn't displayed properly. https://gitlab.freedesktop.org/drm/amd/-/issues/1390~~
=> Use DRM_CAP_CURSOR_{WIDTH,HEIGTH} for cursor buffer

src/steamcompmgr.cpp
This fixes a Clang failure, and ensures we don't blow up the stack on
big cursor sizes.
Closes: https://github.com/Plagman/gamescope/issues/140
=> steamcompmgr: allocate cursor buffer on heap

src/drm.cpp
This is no longer needed as of Linux 5.10.
Closes: https://github.com/Plagman/gamescope/issues/67
~~Submitting as a draft, waiting for a stable kernel release.~~ Known to be broken on 5.9.3.
=> Remove ALLOW_MODESET workaround

src/main.cpp
Right now scale games by default to 720p even if the screen is 1080p.
This happens when -w/-h is *not* specified.
Instead, don't scale the game by default. This means using a 720p
window when nested (shouldn't change anything), and using the screen's
resolution when embedded.
=> Don't scale games by default in embedded

meson.build
emersion/libliftoff@470af77869bea2d005973d7e7f0c2c08cc838e6a changed the name of the pkg-config dependency to `libliftoff` instead of just `liftoff`
=> Update libliftoff pkg-config dependency name

src/steamcompmgr.cpp, src/wlserver.cpp, src/wlserver.hpp
This fixes a state mismatch between wlserver and steamcompmgr. steamcompmgr could have old Wayland surface IDs stored in `win`. This would blow up once another Wayland object re-uses the ID:
```
gamescope: types/wlr_surface.c:560: wlr_surface_from_resource: Assertion `wl_resource_instance_of(resource, &wl_surface_interface, &surface_interface)' failed.
```
Stack trace:
```
#0  0x00007fe8ac9deef5 in raise () at /usr/lib/libc.so.6
#1  0x00007fe8ac9c8862 in abort () at /usr/lib/libc.so.6
#2  0x00007fe8ac9c8747 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007fe8ac9d7646 in  () at /usr/lib/libc.so.6
#4  0x0000562af010058d in wlr_surface_from_resource (resource=0x60c000277cc0)
at ../subprojects/wlroots/types/wlr_surface.c:560
#5  0x0000562af0030eed in wlserver_get_surface(long) …
```
=> Introduce wlserver_surface

src/drm.cpp, src/main.cpp, src/main.hpp
Remove the -l option. Introduce a -L option to disable libliftoff.
Don't use the same option to avoid muscle memory issues.
=> Use libliftoff by default

src/cvt.cpp
Regressed by b380f3fbf24e. Both gamescope and wlroots define `generate_cvt_mode`.
```
$ meson setup --force-fallback-for=libliftoff /tmp/gamescope_build
$ meson compile -C /tmp/gamescope_build
[...]
src/cvt.cpp:23:10: fatal error: 'backend/drm/cvt.h' file not found
#include "backend/drm/cvt.h"
^~~~~~~~~~~~~~~~~~~
1 error generated.
```
=> Unbreak build with system wlroots 0.13.0

.github/workflows/main.yml, meson.build, meson_options.txt, protocol/gamescope-pipewire.xml, protocol/meson.build, src/main.cpp, src/main.hpp, src/pipewire.cpp, src/pipewire.hpp, src/rendervulkan.cpp, src/rendervulkan.hpp, src/sdlwindow.cpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/wlserver.cpp
Tested with:
gst-launch-1.0 pipewiresrc path=<node ID> ! videoconvert ! xvimagesink
To automatically find the PipeWire node ID:
gst-launch-1.0 pipewiresrc "path=$(pw-dump | jq '.[] | select(.info.props["node.name"] == "gamescope") | .id')" ! videoconvert ! xvimagesink
Closes: https://github.com/Plagman/gamescope/issues/213
=> Expose a PipeWire stream

src/pipewire.cpp, src/pipewire.hpp
This allows us to have more control over the buffers, in particular delay their destruction until after the steamcompmgr thread is done with them. 
Depends on https://github.com/Plagman/gamescope/pull/219
=> pipewire: allocate our own buffers 

.gitmodules, meson.build, src/steamcompmgr.cpp, subprojects/packagefiles/stb/meson.build, subprojects/stb.wrap
Allows us to use this as a Meson subproject which means that recursive cloning doesn't matter (Meson resolves it for subprojects).
Given this subproject doesn't have a meson file, doing subproject() on it would fail, so:
Make a wrap file with an overlay that declares a proper dependency.
Signed-off-by: Joshua Ashton <joshua@froggi.es>
=> meta: Use wrap file for STB rather than submodule

src/wlserver.cpp
When gamescope has cap_sys_nice capability, then `secure_getenv` used
by libxkbcommon does not load the keymap configuration from
environment. So the environment variables have to be manually read from
gamescope.
Without `XKB_DEFAULT_LAYOUT` it is not possible to load other keymaps
than US.
An alternative would be to add command line parameters to gamescope for all these variables.
=> wlserver: Force reading XKB_DEFAULT_* variables

meson.build, src/drm.cpp, src/rendervulkan.cpp, src/rendervulkan.hpp, src/steamcompmgr.cpp, src/wlserver.cpp, src/wlserver.hpp
Closes: https://github.com/Plagman/gamescope/issues/16
=> Drop all GL bits

src/drm.cpp, src/wlserver.cpp
GCC 11 + Clang 13 report:
```c++
src/wlserver.cpp: In function 'void wlserver_new_surface(wl_listener*, void*)':
src/wlserver.cpp:430:30: warning: comparison of integer expressions of different signedness: 'long int' and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
430 |                 if (s->wl_id == id && s->wlr == nullptr)
|                     ~~~~~~~~~^~~~~
src/drm.cpp: In function 'void page_flip_handler(int, unsigned int, unsigned int, unsigned int, unsigned int, void*)':
src/drm.cpp:187:53: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
187 |         drm_verbose_log.debugf("page_flip_handler %lu", flipcount);
|                                                   ~~^   ~~~~~~~~~
| …
```
=> Silence some compiler warnings

.github/workflows/main.yml
Ensures a feature doesn't get auto-disabled because a dep isn't
found.
=> ci: turn on auto features

meson.build, protocol/gamescope-input-method.xml, protocol/meson.build, src/ime.cpp, src/ime.hpp, src/wlserver.cpp, src/wlserver.hpp
This allows a Wayland client to send arbitrary UTF-8 text to the
currently focused X11 client. Useful for virtual keyboards.
We generate a keymap on-the-fly suitable for the text to type.
Tested with https://git.sr.ht/~emersion/wl-ime-type.
Closes: https://github.com/Plagman/gamescope/issues/205
=> Add IME protocol

.gitmodules, src/wlserver.cpp
Depends on https://github.com/swaywm/wlroots/pull/3289
=> Disable Xwayland touch pointer emulation

src/steamcompmgr.cpp
Helps with launchers like FO:NV and other games where we end up having the visuals disjoint from what we actually want to input to.
Signed-off-by: Joshua Ashton <joshua@froggi.es>
=> steamcompmgr: Resolve transient links before determining input focus

src/composite.comp, src/main.cpp, src/rendervulkan.cpp, src/rendervulkan.hpp
Adds a --composite-debug flag for displaying frame markers on alternating corners of the screen or rotating in a localized square when compositing.
Signed-off-by: Joshua Ashton <joshua@froggi.es>
=> rendervulkan: Add --composite-debug

src/composite.comp, src/rendervulkan.cpp
We must blend in linear space, not SRGB space or we get these horrible browns.
The surface should already have premultiplied alpha.
Gets us to how we look with planes when blending.
Before:
After:
I modified MangoApp very quickly to have a transparent overlay that would do this: https://github.com/Joshua-Ashton/MangoHud/tree/test-app-blending
=> rendervulkan: Multiple blending fixes

src/steamcompmgr.cpp
The PNG spec says that alpha is not premultiplied, so we need to do that.
(Although there are some things that do use PNG with premultiplied alpha... but let's just ignore that for now and go with the PNG spec and what we are getting exported to us to use on Deck.)
Cursor in X must have premultiplied alpha, our blending setup breaks a lot if this is not true.
=> steamcompmgr: Fix crusty cursor in some scenarios

src/steamcompmgr.cpp
Regressed by 296a3d498d02 + 06cb10683aac. From [error log](https://github.com/Plagman/gamescope/files/7713443/gamescope-3.10.log):
```c++
$ export CC=clang CXX=clang++ CXXFLAGS=-stdlib=libc++
$ meson setup _build
$ meson compile -C _build
[...]
../src/steamcompmgr.cpp:270:41: error: implicit instantiation of undefined template 'std::array<commit_t, 2>'
std::array<commit_t, HELD_COMMIT_COUNT> g_HeldCommits;
^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
^
../src/steamcompmgr.cpp:1160:50: error: implicit instantiation of undefined template 'std::array<BaseLayerInfo_t, 2>'
std::array< BaseLayerInfo_t, HELD_COMMIT_COUNT > g_CachedPlanes = {};
^
/usr/include/c++/v1/__tuple:219:64: note: template is …
```
=> steamcompmgr: unbreak build with libc++

src/sdlwindow.cpp, src/steamcompmgr.cpp
Closes: #324
With this we get `refs: 0` on close and `refs: 1` with no windows (held commit).
=> steamcompmgr: Fix fd leaks + some X errors

src/steamcompmgr.cpp
Only should try to find overrides if we have a focus (ie. focusing the right appid) and only of the appid we want.
=> steamcompmgr: Fix transient override focus crash

src/sdlwindow.cpp
Annoying to have the cursor moving around or the game view having a moment when we're not focused on the window.
=> sdlwindow: Only process mouse motion when we're focused

src/rendervulkan.cpp
Need to use our queueFamilyIndex as the src.
Closes #338
=> rendervulkan: Fix release barrier

src/steamcompmgr.cpp
Any reasonable std::vector implementation probably just clears, but technically:
> Unless otherwise specified, all standard library objects that have been moved from are placed in a "valid but unspecified state", meaning the object's class invariants hold (so functions without preconditions, such as the assignment operator, can be safely used on the object after it was moved from):
https://en.cppreference.com/w/cpp/utility/move
=> steamcompmgr: Fix undefined state of wayland_commit_queue after move.

src/sdlwindow.cpp, src/sdlwindow.hpp, src/steamcompmgr.cpp
Instead of using the default "gamescope" title for the SDL window, this
makes the SDL window title be updated with the focused window's title
whenever a window is focused or whenever the focused window's title is
changed. "gamescope" is still used whenever a title cannot be obtained.
=> Update SDL window title from the focused window's title.

src/drm.cpp, src/drm.hpp, src/steamcompmgr.cpp
Makes it so that we don't forget about any required modesets we need to undertake, and makes modesetting robust by trying again when compositing (in case the error was not mode but plane related), and falling back to the previous mode if that fails.
If we have no mode to fall back to then we abort, same if we fail our mode fallback commit.
=> drm: Don't forget about modesetting + modesetting robustness

src/rendervulkan.cpp, src/rendervulkan.hpp
Less awkward to use and also fixes a texture leak because the shared_ptr
to the texture is no longer stored in the sampler cache.
=> rendervulkan: Rework sampler cache.

src/drm.cpp
This was doing 90deg logic here, not 270deg.
=> drm: Fix inverted CRTC_Y when rotated

meson.build, src/composite.comp, src/mangoapp.cpp, src/rendervulkan.hpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp
- Pulls in and rebases https://github.com/Plagman/gamescope/pull/289 for mangoapp
- Replace layer border alpha with a border mask to fit more layers
- Bump max layer count to 6
- Fade Plane (Fade outs between switching focus)
- Video Underlay (The actual video)
- Video Streaming UI (Game, App)
- External Overlay (Mangoapp, etc)
- Primary Overlay (Steam Overlay)
- Cursor
- **OR**
- Fade Plane (Fade outs between switching focus)
- Base Plane (Game, App)
- Override Plane (Dropdowns, etc)
- External Overlay (Mangoapp, etc)
- Primary Overlay (Steam Overlay)
- Cursor
- Bring in and rebase mangohud frametime message queue
(Dependent on https://github.com/Plagman/gamescope/pull/353 for now also)
=> mangoapp + requirements

meson.build
In absence of subprojects meson has no reason to look for a C compiler.
But the protocol files require it to compile and thus the build would fail with
```
meson.build:114:0: ERROR: No host machine compiler for "gamescope-xwayland-protocol.c"
```
<details>
<summary>Full log</summary>
```
The Meson build system
Version: 0.60.1
Source dir: /home/alebastr/sources/gamescope
Build dir: /home/alebastr/sources/gamescope/build
Build type: native build
Project name: gamescope
Project version: undefined
C++ compiler for the host machine: ccache c++ (gcc 11.2.1 "c++ (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)")
C++ linker for the host machine: c++ ld.bfd 2.37-10
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ …
```
=> Fix build without subprojects

src/steamcompmgr.cpp, src/steamcompmgr.hpp
Stops misleading hover events from happening while also not intefering with touch.
=> steamcompmgr: Warp cursor off of Steam when cursor is hidden

src/rendervulkan.cpp, src/rendervulkan.hpp, src/shaders/cs_composite_blit.comp
Unused since 76292f0, partially broken and
unnecessary because we should be able to always use the correct VkFormat.
=> rendervulkan: Remove swap channels.

meson.build
Just a small fix for a  build failure on my system.
=> build: link to librt since the pipewire code uses shm_open()

src/drm.cpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/vblankmanager.cpp, src/vblankmanager.hpp, src/xwayland_ctx.hpp
Reworks the VBlank manager to estimate the next draw time using a rolling average when the new draw time was less than the current rolling average, and a max when it goes above to account for spikes.
Includes some tuneables exposed by an atom so we can play with this via xprop or Steam or whatever.
=> Dynamic VBlank Rework

src/pipewire.cpp, src/pipewire.hpp
With the latest version of pipewire, the process callback is no longer automatically called. Instead, you should call pw_stream_trigger_process() when frames are ready, to have the processing callback happen.
Since the only processing we're doing is requesting a buffer, I'm calling that directly from the callback, since that is thread-safe for a single reader.
=> Fixed pipewire stream stopping after a few seconds

src/steamcompmgr.cpp
The cleanup sequence run on X11 I/O error was incomplete. Let's
extract it to a function to make sure it doesn't go out-of-sync
again.
=> steamcompmgr: cleanup on X11 error

src/mangoapp.cpp
The size argument must not include the `long msg_type` field.
Fixes the following ASan error:
=================================================================
==25745==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55cb6beea08a at pc 0x7f118e89525d bp
0x7f117620a8a0 sp 0x7f117620a048
READ of size 50 at 0x55cb6beea08a thread T10
#0 0x7f118e89525c in __interceptor_msgsnd /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_c
ommon_interceptors.inc:3138
#1 0x55cb6b6518ed in mangoapp_update(unsigned long, unsigned long, unsigned long) ../src/mangoapp.cpp:
48
#2 0x55cb6b484dde in imageWaitThreadMain() ../src/steamcompmgr.cpp:521
#3 0x55cb6b538298 in void std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) /usr
/include/c++/11.2.0/bits/invoke.h:61
#4 …
=> mangoapp: fix msgsnd size arg

src/rendervulkan.cpp, src/rendervulkan.hpp, src/shaders/blur.h, src/shaders/cs_composite_blur.comp, src/shaders/cs_composite_blur_cond.comp, src/shaders/cs_gaussian_blur_horizontal.comp, src/shaders/descriptor_set.h, src/steamcompmgr.cpp, src/steamcompmgr.hpp
Essentially just shoves that into the horizontal pass and cleans it out of the normal composite when we go to do vertical and also makes the blur image the same size as the output, which should have been done anwyay to avoid harsh borders.
Closes #426
@DadSchoorse
=> rendervulkan: Support blur for override redirect layer too

src/drm.cpp, src/drm.hpp
These are created/destroyed dynamically by the kernel.
=> drm: add support for DP-MST connectors

src/ime.cpp
Avoids switching the keymap unless necessary.
=> ime: use default keymap if possible

src/sdlwindow.cpp
This changes the mouse button mapping in gamescope to match the mapping in SDL2-2.0.20:src/core/linux/SDL_evdev.c.
Fixes issue #234.
=> sdlwindow: Fix extra mouse button mapping

src/mangoapp.cpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp
This allows us to cross reference pid with the mangoapp layer and get what vulkan engine the focused app is using
=> mangoapp: send focusWindow pid

src/rendervulkan.cpp
Fixes using 1000s of fences which exhausts FDs on NVIDIA.
=> Use timeline semaphores for scratch cmd buffers

src/main.hpp, src/sdlwindow.cpp
https://github.com/Plagman/gamescope/issues/105
Kill the thread on an SDL_WINDOWEVENT_CLOSE in order to handle Alt+F4 events
=> sdlwindow: Handle SDL_WINDOWEVENT_CLOSE

LICENSE, src/drm.cpp, src/drm.hpp, src/main.cpp, src/main.hpp, src/steamcompmgr.cpp
* Raise the soft file descriptor limit for the process at startup. Each VkFence will consume a file descriptor on the NVIDIA Vulkan driver, and Gamescope creates 1024, equal to the usual default file descriptor limit, guaranteeing resource exhaustion.
* Don't attempt to use the GAMMA_LUT CRTC property when it is not supported.
=> Fix some issues when running on the NVIDIA Vulkan driver

README.md, meson.build, src/main.cpp, src/main.hpp, src/mangoapp.cpp, src/rendervulkan.cpp, src/rendervulkan.hpp, src/sdlwindow.cpp, src/shaders/NVIDIAImageScaling/NIS/NIS_Config.h, src/shaders/NVIDIAImageScaling/NIS/NIS_Main.glsl, src/shaders/NVIDIAImageScaling/NIS/NIS_Main.hlsl, src/shaders/NVIDIAImageScaling/NIS/NIS_Scaler.h, src/shaders/NVIDIAImageScaling/README.md, src/shaders/NVIDIAImageScaling/licence.txt, src/shaders/cs_nis.comp, src/shaders/cs_nis_fp16.comp, src/shaders/descriptor_set.h, src/steamcompmgr.cpp, src/xwayland_ctx.hpp
This PR adds support for selecting NVIDIA Image Scaling as the Gamescope upscaler implementation. It can be enabled by passing the -Y or --nis-upscaling option to Gamescope.
=> Support for NVIDIA Image Scaling

src/sdlwindow.cpp, src/wlserver.cpp, src/wlserver.hpp
handle touch events properly and disable SDL mouse emulation to avoid getting mouse events from the touch input.
=> handle SDL touch events

src/ime.cpp
These codepoints cannot be typed into CEF when translated into actual keysyms with xkb_utf32_to_keysym()
The first range is especially important if we're going to enable nice incremental Hangul typing.
=> ime: Force Hangul Compat Jamo codepoints to use generic keysyms

src/main.cpp, src/main.hpp, src/rendervulkan.cpp
allows selecting a preferred Vulkan device for compositing, for example
to use the iGPU over the dGPU.
should help #498.
=> add --prefer-vk-device option

src/drm.cpp
Avoids picking 4K@30Hz and other modes which feel really bad.
Happens on a lot of USB C -> HDMI adapters on displays that support 4K@60, even if they advertise support for it online.
=> drm: Always prefer modes > 60Hz to any others

README.md
At some point someone must have changed the meaning of the `-n` flag and `Super-N` keyboard shortcut, this PR updates the README to reflect those changes
=> Make README consistent with changes to nearest neighbor flag and keyboard shortcut

protocol/gamescope-input-method.xml, src/ime.cpp
Closes: https://github.com/Plagman/gamescope/issues/616
Example client patch for [wl-ime-type](https://git.sr.ht/~emersion/wl-ime-type)'s `gamescope` branch:
```diff
diff --git a/main.c b/main.c
index 3db99a283f2f..dd5e5058e5a5 100644
--- a/main.c
+++ b/main.c
@@ -32,7 +32,7 @@ static const struct gamescope_input_method_listener ime_listener = {
static void registry_handle_global(void *data, struct wl_registry *registry, uint32_t name, const char *iface, uint32_t version)
{
if (strcmp(iface, gamescope_input_method_manager_interface.name) == 0) {
-		ime_manager = wl_registry_bind(registry, name, &gamescope_input_method_manager_interface, 1);
+		ime_manager = wl_registry_bind(registry, name, &gamescope_input_method_manager_interface, 2);
} else if (seat == NULL && strcmp(iface, …
```
=> ime: add move_{up,down} actions

src/ime.cpp
More closely simulate a human pressing by holding the last (or only) key in
key pressed for 30ms before releasing. The key is released automatically
after the timer expires or just in time before a subsequent injected key.
**This really needs another set of eyes to code review!**
=> ime: Delay release of last keypress

src/wlserver.cpp
Steam also wants to read the wl_output global itself (outside of X stuff).
=> wlserver: Expose base wl_output to non-xwayland server clients

src/wlserver.cpp
1. output plugged in, gamescope creates new wlr_output and sends a wl_registry.global event
2. client sees it, sends a wl_registry.bind request
3. output plugged out, gamescope sends a wl_registry.global_remove event and destroys the wlr_output
4. gamescope receives the wl_registry.bind request, but the wlr_output no longer exists
5. client receives the wl_registry.global_remove event
=> wlserver: explain why filter_global may need to handle NULL wlr_output

src/drm.cpp, src/drm.hpp
Fixes an issue where we would use an invalid connector because
the MST connector object got destroyed from our last CRTC set.
This avoids just using it again.
=> drm: Don't re-zero connector CRTCs we already have zero-ed.

src/steamcompmgr.cpp
Replaces the abort here to be more lenient.
Some intense connector hotplugging could be occuring and the connector could become destroyed before we had a chance to use it as we hadn't reffed it in a commit yet.
=> steamcompmgr: Be more lenient when failing flips

src/steamcompmgr.cpp
Xwayland blits sometimes send us duplicate commits when strange things happen such as connector hotplugs.
=> steamcompmgr: Avoid duplicate commits

src/drm.cpp, src/drm.hpp, src/main.cpp, src/wlserver.cpp
The default behavior without the --force-orientation argument will remain the same to ensure compatibility is not broken. For devices that require Gamescope to be rotated, such as the One Xplayer this is now possible with these changes. 
Ideally in the future we'll want to make use of the kernel quirks, but for now this should be fine.
=> Add --force-orientation option

src/drm.cpp
If I'm understanding the flow of code here correctly, what should be happening here is `vdisplay` and `hdisplay` should be regular by default and when `g_drmEffectiveOrientation` is updated to either 90 or 270 degrees then the values should become inverted.
=> drm:  fix an issue where g_nOutputWidth and g_nOutputHeight weren't updated 

src/rendervulkan.cpp
blit pipelines use 132 bytes now.
=> rendervulkan: Update push sizes.

meson.build, src/drm.cpp
Ensures the system has the proper dependency, and avoids hardcoding the path.
Need to wait for SteamOS to ship hwdata 0.362.
=> build: use hwdata's pkg-config file

src/wlserver.cpp, src/wlserver.hpp
SDL touch_ids are not aggressively recycled like libinput. This leads for a bad check to see how many touches are 'down'.  Using a set of touch_ids to keep track so we can remove the deviation.
This issue is a kind of a sleeper as the touch events (only up and down) will fall back to click events of the touch_id is out of bounds. 
https://github.com/Plagman/gamescope/issues/682
=> Fix for the SDL / Libinput touch_id deviation. 

src/steamcompmgr.cpp
POLLIN waits for the buffer to be ready for reading, POLLOUT waits for writing.
In gamescope we're reading client buffers, so we need to use POLLIN.
We were using POLLOUT to workaround an amdgpu bug, but that got fixed in kernel 5.15, so shouldn't be necessary anymore.
=> Wait for POLLIN instead of POLLOUT

src/sdlwindow.cpp
Passing the `SDL_WINDOW_ALLOW_HIGHDPI` flag to `SDL_CreateWindow` will enable the SDL Wayland videodriver's HiDPI support. This allows gamescope to render in display pixels, removing the need for the Wayland compositor to upscale (causing blurriness).  
Closes: #551
=> sdlwindow: request HiDPI window

src/main.cpp, src/meson.build, src/steamcompmgr.cpp
Runtime is still broken: need to file bugs as those are non-trivial.
Depends on https://github.com/emersion/libliftoff/pull/52
=> Unbreak build on FreeBSD

src/steamcompmgr.cpp
Handle the return code of system() call to log it properly and silence a warning of the compiler.
This comes as preliminary work to debug (and hopefully fix) #716
=> Add basic handling of system() call

src/main.cpp, src/main.hpp, src/sdlwindow.cpp
Add support to grab the keyboard in nested mode through either a flag (-g/--grab) or a keybinding (Super+G).  I also added " (grabbed)" to the title as an indication to the user when the keyboard is grabbed.
Note: This will NOT work when using XWayland
=> Add support for grabbing the keyboard

src/main.cpp, src/rendervulkan.cpp, src/shaders/blit_push_data.h, src/shaders/colorimetry.h, src/shaders/composite.h, src/shaders/cs_composite_rcas.comp, src/shaders/cs_gaussian_blur_horizontal.comp, src/shaders/cs_rgb_to_nv12.comp, src/shaders/descriptor_set.h, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/xwayland_ctx.hpp
adds BT.2446 Method A inverse tone mapping as per §4 Table 2-4 from https://www.itu.int/dms_pub/itu-r/opb/rep/R-REP-BT.2446-1-2021-PDF-E.pdf
makes SDR apps look more like real HDR
has really good results imo
though it can be a bit intense at times
=> add the ability to use inverse tone mapping on apps that output SDR

src/drm.cpp
Fixes gamescope sometimes segfaulting for me.
=> Check for nullptr connector in drm_prepare

meson.build
This should allow building gamescope against a system installation of openvr.
The pkgconfig file of openvr specifies `openvr` as the name of the dependency: https://github.com/ValveSoftware/openvr/blob/1a0ea26642e517824b66871e6a12280a426cfec3/src/openvr.pc.in#L6
=> Fix openvr dependency name

src/meson.build
libdisplay-info 0.1.x still works fine for gamescope. Bump maximum version to allow it.
=> build: bump libdisplay-info maximum version

src/vr_session.hpp
This should *actually* allow using system installations of openvr
=> vr_session: fix openvr include

src/sdlwindow.cpp
SDL_GetWindowSize() gives width and height in screen coordinates which should be used for scaling mouse movements. The output size we should be rendering should be in pixels which is given by
SDL_GetWindowSizeInPixels().
Fixes #796.
=> sdlwindow: fix HiDPI handling

src/sdlwindow.cpp
Prevents a double free that might occur if icon_surface is not allocated in the conditional following the free.
Duplicates part of #829, but seems like it would be good to separate that PR into two anyways.
=> sdlwindow: set icon_surface to nullptr after free

src/main.cpp
With tabs, it is not aligned in some terminals.
=> Replace tabs with spaces in help

src/drm.cpp
On certain configurations the EDID retrieval and parsing seems to fail, leading to create_patched_edid accessing out of bounds indexes on a zero length vector.
Fixes #860.
=> Avoid out of bounds accesses in drm.cpp

src/main.cpp, src/rendervulkan.cpp, src/rendervulkan.hpp
This is essentially a fix for [src/rendervulkan.cpp:3075](https://github.com/ValveSoftware/gamescope/tree/378cfa5b7bb6fd005c32241330938b7f1bd9c881/src/rendervulkan.cpp#L3075) (before this commit).
Instead of first selecting a queue and later failing, if the selected queue can't be used for presenting, this patch considers the fact, *when* selecting a queue.
As a result quite a bit of code had to be re-ordered to make sure the surface already exists, when selecting the queue.
This is not just an academic exercise, but necessary e.g. for running nested on the nvidia-driver, which doesn't support presenting with the normally selected compute queue.
While that can be worked around by setting `ENABLE_VKBASALT=1`, this seems like a more appropriate fix, given that nothing in the spec seems to …
=> vulkan: Check if selected queue can be used

src/steamcompmgr.cpp, src/steamcompmgr_shared.hpp, src/wlserver.cpp
This avoids a problem where frame callback is reported before we have actually committed to display a surface. This could lead to skipping where application commits a new surface before the current surface will be queued up for display. This breaks FIFO rules in e.g. Vulkan. A scenario where this matters is when GPU is rendering slower than refresh rate.
Also avoids a problem where the commit queue can grow large since frame callbacks will be pumped faster than the GPU is able to process the frames.
At least Mutter behavior is similar here, so I think this is the correct interpretation.
Also fixes KHR_present_wait in Xwayland. Xwayland uses frame callback to signal PRESENT_COMPLETE and this fixes that.
=> Don't send frame callback before we have actually committed.

src/rendervulkan.cpp
Currently gamescope tries to use a high priority queue whenever we have CAP_SYS_NICE.
I think that Nvidia only supports this feature on Pascal and newer (https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-470-42-01-beta/181536), so gamescope can fail to start on older cards with CAP_SYS_NICE 
(e.g. https://github.com/HoloISO/holoiso/issues/262#issue-1260909682).
If this happens, just fall back to a regular-priority queue.
Many thanks.
=> Fallback to regular-priority queue when vkCreateDevice fails

src/mangoapp.cpp
This way mangoapp knows what resolution gamescope is running and can adjust accordingly. This should resolve issues on various handhelds where `--force-orientation left` caused incorrect rendering of mangoapp
=> mangoapp: report output size to mangoapp

README.md, src/main.cpp
One of my friends rage-uninstalled Linux as he wasn't able to set his shooter to a streched resolution.
Therefore I want to prevent other people from suffering **that** much and made the already existing option accessible.
As it was superfluous, I removed the option to explicitly force integer scaler. This might be a breaking change.
Some points to discuss:
- Shouldn't we do the same for the upscaler filter?
At the moment there are multiple options that contradict each other. (-U, -Y, -n)
- On my machine the `README.md` isn't correct about building instructions as the binary is at `build/src/gamescope`.
Is this a mistake?
- I thought about implementing shortcuts to cycle through the scalers / filters.
Would this be useful to anybody or would explicit shortcuts make more sense?
Related: …
=> Added option to set scaler and filter

src/steamcompmgr.cpp
The --adaptive-sync flag is not used during vrr atom update so it's value get's overwritten with 0 thus disabling the VRR in the process.
=> steamcompmgr: Fix enabling VRR from commandline

src/drm.hpp, src/main.cpp, src/sdlwindow.cpp
Tested for 3.11.51 only, but should also apply to master.
Fixes:
```
[34/45] c++ -Igamescope.p -I. -I.. -Iprotocol -I/usr/include/libdrm -I/usr/include/SDL2 -I/usr/include/pixman-1 -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/stb -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++14 -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-invalid-offsetof -Wno-unused-const-variable -DHAVE_PIPEWIRE=1 '-DHWDATA_PNP_IDS="//usr/share/hwdata/pnp.ids"' -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_REENTRANT -pthread -MD -MQ gamescope.p/src_drm.cpp.o -MF gamescope.p/src_drm.cpp.o.d -o gamescope.p/src_drm.cpp.o -c ../src/drm.cpp …
```
=> Fix compilation with GCC13

src/main.cpp, src/rendervulkan.cpp
not every platform uses nullptr, some use 0LL or ((void*)0) directly.
closes #917
=> fix null handle for nul surface

src/meson.build
In version 12.3.0 glslangValidator was renamed to glslang. This commit checks for both the old glslangValidator name and the new glslang
=> glslang: check for renamed bin

README.md, src/main.cpp, src/sdlwindow.cpp, src/sdlwindow.hpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/wlserver.cpp, src/xwayland_ctx.hpp
Tested with `gamescope gvim`.  This PR adds support for copying/pasting utf-8 text for both the clipboard and the primary selection.  In the event that SDL_CLIPBOARDUPDATE doesn't get triggered (for example, when running gamescope as XWayland under sway), I've implemented the keybinding `Super + C` to sync both the clipboard and primary selection with gamescope.  As of now, this PR only supports Xwayland application windows under gamescope.  I don't have much experience with Xlib, so any feedback is appreciated.
Closes #303
=> Add clipboard support

src/main.cpp
Looks like this was missed by e631460bc5a1ce53af994cf7f0c9f9e96325a298
=> Remove reference to non-existent key bind

layer/VkLayer_FROG_gamescope_wsi.cpp, layer/VkLayer_FROG_gamescope_wsi.json.in, protocol/gamescope-swapchain.xml, protocol/gamescope-xwayland.xml, protocol/meson.build, src/drm.cpp, src/main.cpp, src/rendervulkan.cpp, src/rendervulkan.hpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/vblankmanager.cpp, src/vblankmanager.hpp, src/wlserver.cpp, src/wlserver.hpp, src/xwayland_ctx.hpp
Slightly messy, big refactors of the layer + protocol here.
=> Implement VK_GOOGLE_display_timing

src/sdlwindow.cpp
Normally when the user activates a shortcut like Super+S, gamescope will pass through the keydown event for Super+S to the game. However, when the key is released, gamescope consumes the keyup event, making it so the game doesn't realize that the key was released and just keeps it held down.
This issue is pretty old (#577 was created in 8/2022 and this issue was mentioned in #335 in 12/2021). This issue would've been fixed (mostly as a side effect) in the aforementioned pull request #335 but a collaborator mentioned that they'd rather just handle this issue the right way and make shortcuts fully configurable rather than include the option to disable them (like in #335) or fix the "key getting stuck" issue (my fix). While I agree that that would be a better solution, I would really …
=> Consume KeyDown event when the user is activating a shortcut

protocol/gamescope-control.xml, src/main.cpp, src/main.hpp, src/rendervulkan.cpp, src/rendervulkan.hpp, src/sdlwindow.cpp, src/shaders/blit_push_data.h, src/shaders/composite.h, src/shaders/cs_composite_blit.comp, src/shaders/cs_composite_blur.comp, src/shaders/cs_composite_blur_cond.comp, src/shaders/cs_composite_rcas.comp, src/shaders/cs_easu.comp, src/shaders/cs_easu_fp16.comp, src/shaders/cs_gaussian_blur_horizontal.comp, src/shaders/cs_nis.comp, src/shaders/cs_nis_fp16.comp, src/shaders/cs_rgb_to_nv12.comp, src/shaders/descriptor_set.h, src/steamcompmgr.cpp, src/wlserver.cpp
Adds a "Sharp" filter which is a band-limited pixel filter based on
https://github.com/Themaister/Granite/blob/master/assets/shaders/inc/bandlimited_pixel_filter.h
by Hans-Kristian.
Also emulates bilinear sampling for HDR10 PQ content to blend in the right space.
Closes: https://github.com/ValveSoftware/gamescope/issues/712
=> rendervulkan: Add PIXEL filter (band-limited pixel filter)

subprojects/stb.wrap
Newer revisions of nothings/stb have switched to stb_image_resize2.h and moved the original header to deprecated/stb_image_resize.h since [1]. Pin down the version to prevent future breaking changes.
[1]: https://github.com/nothings/stb/commit/c4bbb6e75f688318b2df2b70c2df2d641c1a8481
=> Lock stb to last revision with stb_image_resize.h

src/rendervulkan.hpp
Upcoming FreeBSD 14.0 ships with libc++ 16. However, libc++ 17 isn't affected due to header bootlegging:
```c++
In file included from ../src/drm.cpp:21:
In file included from ../src/drm.hpp:11:
In file included from /usr/include/c++/v1/span:600:
In file included from /usr/include/c++/v1/functional:526:
In file included from /usr/include/c++/v1/__functional/boyer_moore_searcher.h:27:
In file included from /usr/include/c++/v1/vector:321:
In file included from /usr/include/c++/v1/__format/formatter_bool.h:20:
In file included from /usr/include/c++/v1/__format/formatter_integral.h:32:
In file included from /usr/include/c++/v1/locale:202:
In file included from /usr/include/c++/v1/__locale:21:
/usr/include/c++/v1/mutex:12:2: error: 1
12 | #error bootlegging check
|  ^
```
=> Unbreak build with libc++ 16

layer/VkLayer_FROG_gamescope_wsi.cpp
Hi there,
Minor refactor edit to use the C++11 library API `std::any_of` instead of its previous '03 idiom.
Let me know if these C++ modernisation refactors are ok, happy to send in some more if it helps! (But what C++ standard should one target by default?)
Thanks! :smile:
=> layer: Prefer C++11 `std::any_of` over '03 `std::find_if` style

src/main.cpp
I've replaced tabs with spaces because tabs are usually have width of 8 characters in terminals.
=> Indentation fix in help message

layer/VkLayer_FROG_gamescope_wsi.cpp
Hi there!
After @Joshua-Ashton's [previous comment](https://github.com/ValveSoftware/gamescope/pull/989#issuecomment-1765193024) that the project is `C++20`, I have updated the [previous changeset merged](https://github.com/ValveSoftware/gamescope/pull/989) once more to reflect this, let me know what ya think!
Major pros for this `C++20` version:
* `.{begin,end}` member-functions unneeded! :tada: 
* **Very standardised**; instead of custom lambdas for a simple comparison, where one has to worry about datatype of elements to be scanned, reference capturing & prefect-forwarding concerns and blah blah blah, _**everything**_ can use the awesome C++ standardised approach, `std::bind_front`. :crown:
* **Scoping of comparator variable**; because one does not need use lambda syntax anymore as …
=> layer: Prefer C++20 ranges::any_of over '11 style

src/steamcompmgr.cpp
Makes testing with HDR Vulkan layers easier
=> rendervulkan: apply hdr-debug-force-output option in nested mode

src/meson.build
=> Unbreak build on FreeBSD via epoll-shim

src/steamcompmgr.cpp
If the queue contains two commits with a desired time set in the future, keep the second one in the queue instead of discarding it.
=> steamcompmgr: don't erase multiple commits with future desired time

protocol/gamescope-commit-queue-v1.xml, protocol/meson.build, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/steamcompmgr_shared.hpp, src/wlserver.cpp, src/wlserver.hpp, src/xwayland_ctx.hpp
Same as https://github.com/ValveSoftware/gamescope/pull/1026 but with a vendored protocol extension.
=> Add support for vendored commit-queue-v1

src/rendervulkan.cpp
If you have a modifier with image compression that is only support for some image formats like :
- B8G8R8A8_UNORM : compression supported
- B8G8R8A8_SRB   : compression not supported
Then the render will not use compression but the modifier indicates it is present, so the compositor will try to make use of the side compressed data and this will lead to corruptions.
This fixes issues on Intel HW of Gfx9 generations.
=> renderervulkan: only consider modifiers support all the image properties

src/steamcompmgr.cpp
The "target FPS" feature divides vblank to achieve a target refresh rate. Previously, the target frame time was divided by the divisor again, making it way too small and nonsensical. Correctly calculate this by multiplying instead of dividing.
Since the real refresh rate may be odd, apply the multiplier after dividing to avoid rounding error.
=> steamcompmgr: Fix calculated refresh cycle for present timing

src/drm.cpp, src/drm.hpp
The first commit fixes a use-after-free and is a backport candidate.
The second is a refactor and the third uses the newly introduced drm_blob helpers to avoid leaks of mode and lut tracking.
=> drm_blob abstraction and lifetime management fixes

src/drm.cpp
=> drm: fix NPE while in headless mode

src/meson.build, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/xwayland_ctx.hpp
Taking a page out of XEyes' book to get the cursor position (even when the cursor is grabbed, etc) by only doing so when we get a RawMotion event -- and only register for those when we know there's a cursor image that we would want to render.
This is a kinda crap workaround for the fact that we cannot directly just recieve information about the cursor from the XServer, even as the X11 WM due to cursor grabbing, input masking and other such nonsense.
An alternative would be using something like libei and having XTest funnel through that -- however that needs work to be functional on nested compositors.
=> steamcompmgr: Use XInput2 RawMotion events as a hint to update cursor pos

src/rendervulkan.cpp
Rendervulkan.cpp: move calls to bInit() outside of assert, so that bInit() still runs when gamescope is built with NDEBUG set
I just realized this was an issue today, and I'm not aware of any github issues talking about this.
I think you'd have to specifically pass the meson option `-Db_ndebug=true` to run into this issue, since meson doesn't set NDEBUG if you just specify `--buildtype=release`.
=> Fix issue w/ gamescope crashing if built w/ "-Db_ndebug=true"

src/meson.build
On a Debian system with `libavif-dev` version `0.11.1` compiling fails with the following errors:
```
../src/steamcompmgr.cpp: In lambda function:
../src/steamcompmgr.cpp:3205:61: error: ‘avifImage’ {aka ‘struct avifImage’} has no member named ‘clli’
3205 |                                                 pAvifImage->clli.maxCLL = maxCLLNits;
|                                                             ^~~~
../src/steamcompmgr.cpp:3206:61: error: ‘avifImage’ {aka ‘struct avifImage’} has no member named ‘clli’
3206 |                                                 pAvifImage->clli.maxPALL = maxFALLNits;
|                                                             ^~~~
../src/steamcompmgr.cpp:3221:51: error: ‘avifEncoder’ {aka ‘struct avifEncoder’} has no member named ‘quality’
3221 | …
```
=> define minimum libavif version in src/meson.build

src/vr_session.cpp
OpenVR 2.0.10 added some previously reserved enum values. *Though one still remains*
This PR makes Gamescope require OpenVR 2.0.10.
=> vr_session: update to OpenVR 2

src/reshade_effect_manager.cpp
Hi there,
This PR condenses and summaries some common code-fragments in `ReshadeUniform::copy`.
I would squash this to one commit, however I kept the history for code-review ease and purposes. Please feel free when this PR is fine, to condense everything into one commit for git-history reasons if you like! :smile: 
Happy to answer any questions on the design of the changeset. The source-code uses mixed naming standards as tried to match the style previously (which was also mixed).
Hope this helps and thanks! :smile:
=> reshade: Summarise code-section of `ReshadeUniform::copy`

src/main.cpp, src/main.hpp, src/wlserver.cpp
The `--mouse-sensitivity`/`-s` command line option allows the user to set the value `g_mouseSensitivity` which is used to scale the mouse movement in `wlserver_mousemotion`.
This works well for reducing sensitivity: sub-pixel increments taken into account to avoid jerky cursor movement as a result of rounding.
However, increasing sensitivity results in a loss of precision proportional to the multiplier since it seems mouse movements are only ever given in terms of pixels (i.e. a multiplier of `2.0` causes 2 pixels to be the shortest distance the cursor can be moved. If there is a way to get around this, please let me know).
This change is a possible workaround for #196 and #244, but the main motivation is to allow forcing mouse sensitivity scaling on games that don't respect the host …
=> Add configurable mouse sensitivity

src/wlserver.cpp
If we know that the display only supports one refresh rate (the current refresh rate), send that as part of active display info.
This is useful so clients can determine valid framelimit values.
=> wlserver: always broadcast a refresh rate in gamescope_control

src/steamcompmgr.cpp
`hdr_metadata_blob` is stored in a `BackendBlob` as a `hdr_output_metadata` here:
https://github.com/ValveSoftware/gamescope/blob/master/src/wlserver.cpp#L772
..but is later retrieved as a `hdr_metadata_infoframe` here:
https://github.com/ValveSoftware/gamescope/blob/master/src/steamcompmgr.cpp#L7836
This causes the `memcpy` to fail with an assert, as the data is not of the expected size. Casting to the correct `hdr_output_metadata` and then passing the `hdr_metadata_infoframe` from the `hdmi_metadata_type` member fixes the copy.
This fixes a crash in Control Ultimate Edition (870780), but the issue only presents itself with the unofficial patch that is available here: https://community.pcgamingwiki.com/files/file/2581-control-hdrultrawidedlssrt-patch/, although I'd expect all games that …
=> Fix incorrect casting of HDR metadata blob

src/wayland_backend.cpp
It only caused crashes because of an out of bounds access that is now fixed
=> wayland_backend: allow unmapping subsurfaces

src/meson.build
Includes `protocols_client_src` when building gamescope's executable
The new `wayland_backend.c` needs `xdg-shell-client-protocol.{c,h}` to build.
=> src/meson: include protocols_client_src

src/drm.cpp
gamescope sets a variety of DRM properties that Xorg is unaware of and those properties can make atomic commits fail depending on the state that Xorg proposes.
This change makes gamescope reset some of the drm properties when it quits to prevent Xorg from breaking.
=> drm: Reset drm properties when quitting

src/reshade_effect_manager.cpp
Hi there!
`std::make_shared` works with derived object types. :crown: 
As there is nothing custom about the base object type (no custom deleter, custom `new` operator, stuff like that), `std::make_shared` is the recommended standard way for generating types of `std::shared_ptr`.
It is also simpler too. :wink: 
Thanks and hope this helps!
=> reshade: Prefer `make_shared` over raw `shared_pointer(new X)`

src/reshade_effect_manager.cpp
Hi there! :smile: 
Following the positive response of PR:#992, this PR normalises additional standard algorithms (in)to using a C++20 approach of `std::ranges` and `std::bind_front` :crown: . 
Hope this helps!
=> reshade: Prefer `std::ranges` and `std::bind_front` over custom lambdas

src/wlserver.cpp
Don't access xwayland_servers vector in global filter while clearing the vector.
Avoids a segfault due to
```
(gdb) bt
#0  gamescope_xwayland_server_t::get_client (this=0x55c403edfcb0) at ../src/wlserver.cpp:753
#1  filter_global (client=0x55c40417a3b0, global=0x55c4040ba230, data=<optimized out>) at ../src/wlserver.cpp:1371
#2  0x00007f1ce72ba750 in wl_global_remove () at /usr/lib/libwayland-server.so.0
#3  0x000055c4024b7ad7 in wlr_global_destroy_safe (global=0x55c4040ba230) at ../subprojects/wlroots/util/global.c:35
#4  0x000055c4024aada0 in wlr_output_destroy_global (output=output@entry=0x55c404101ef0) at ../subprojects/wlroots/types/output/output.c:166
#5  0x000055c4024aae30 in wlr_output_destroy_global (output=0x55c404101ef0) at ../subprojects/wlroots/types/output/output.c:151
#6 …
```
=> wlserver: fix exit segfault

src/wlserver.cpp
Refactoring to allow RVO to work better w/ std::optional.
Inspired by: https://www.youtube.com/watch?v=0yJk5yfdih0
I did make sure to check that my changes actually eliminated potential copies/temporaries w/ the latest version of gcc in godbolt. I based those tests on the examples that were linked at: https://github.com/lefticus/cpp_weekly/issues/285
=> wlserver.cpp: improve RVO/copy elision

src/main.cpp
This PR introduces a new `--backend` CLI option which allows user to explicitly select the rendering backend.
Also drops `--headless` and `--openvr` options as redundant.
The option is useful e.g. when autodetected backend doesn't work. See #1218 as an example where Wayland backend crashes on Polaris GPUs. With this PR user can set `--backend=sdl` to workaround the issue.
=> Add `--backend` CLI option

src/main.cpp, src/meson.build, src/sdlwindow.cpp, src/x11cursor.cpp
Fix broken build with `sdl2_backend=disabled`. See #1347.
* main: add missing condition in the Wayland fallback.
* sdlwindow: move out `GetX11HostCursor()` into a separate file.
* build: add `x11cursor.cpp`.
=> Fix `sdl2_backend=disabled`

src/main.cpp
Follow up for #1321.
DRM and SDL2 backends could be disabled by build options. So we hide them from user in that case.
=> main: hide disabled backends from user

src/InputEmulation.cpp
The libeis-1.0 pc file already adds this to the include path, so this will break the build
=> InputEmulation: remove explicit libeis header folder

meson.build
Since
https://github.com/ValveSoftware/gamescope/commit/84b486345a0c5c2c1fb828acba7d717694549855 introduced changes to openvr subproject (or maybe before) this package won't compile if `openvr` package is installed on ArchLinux (currently on v2.2.3). Update version requirement to use the subproject if available.
=> Update openvr version requirement

src/main.cpp
Allows the user to set `MANGOHUD_CONFIGFILE` to their own config file.
I assume the temp file that is created is used by steam.
=> mangoapp: Use existing MANGOHUD_CONFIGFILE if set

src/Apps/gamescopereaper.cpp
```
/builddir/gamescope-3.14.23/src/Apps/gamescopereaper.cpp:87:13: error: use of undeclared identifier 'STDIN_FILENO'
87 |             STDIN_FILENO,
|             ^
```
etc
=> gamescopereaper: add missing include

src/Utils/Process.cpp
musl no-ops sched_setscheduler, pthread_setschedparam should work everywhere  
---
the longer story is https://www.openwall.com/lists/musl/2016/03/01/4 (yes, annoying), but this code should work on both glibc and musl so it should be fine
=> utils: make setting/restoring from RT thread work on musl

src/Backends/WaylandBackend.cpp
For nested wayland
Very simple little thing so that if the gamescope window goes invisible (from there being no windows to draw or whatever), if it was fullscreen before, then when it comes back up it'll return to being fullscreen
Yeah, that's all
=> WaylandBackend: Force update fullscreen when returning from not being visible

src/main.cpp
`MANGOHUD_CONFIGFILE` should only be set by gamescope if we're in steamMode. This is causing confusion for regular users as it prevents usage of the standard mangohud config paths
=> mangoapp: only set env in steammode

src/color_bench.cpp, src/color_helpers.cpp, src/color_helpers.h, src/color_helpers_impl.h, src/color_tests.cpp, src/rendervulkan.hpp, src/steamcompmgr.cpp
Unless I were to just add compiler flags to turn off the vla warnings, there were only two ways I saw to fix the VLA warning:
- Use a vector instead of vla
- Make the vla's length a compile time constant. 
I took the latter choice in this PR, because I was unsure of, if and/or to what extent that replacing the VLA w/ a vector could interfere w/ autovectorization. I reckon that w/ LTO, the compiler is currently able to figure out that the VLA's length is always just 17, so that it can optimize as if it was just a normal array w/ compile-time-constant length. 
So replacing the VLA could lead to the compiler making slightly worse codegen.
~~C++ template functions with Non-Type Template Parameters (what a mouthful!) don't seem to be able to be split into a declaration/function prototype in …
=> Clang warning fixes

src/meson.build
Closes: #1390
Patching gamescope-3.14.23 it build just fine:
```
libdisplay-info.so.2 => /usr/x86_64-pc-linux-gnu/lib/libdisplay-info.so.2 (0x00007f30246eb000)
```
A quick runtime test with a plain `$ gamescope -- vkcube` didn't show any obvious problem.
=> subprojects: update libdisplay-info to 0.2.0

src/wlserver.cpp
For whatever reason, when working on upgrading to wlroots .18, I had previously noticed that gamescope would sometimes still segfault (issue  #1364 ), due to a nullptr deref on oPoint->pTimeline.
I had put in a nullptr check for that in my previous wlroots .18 PR, but the check was left out when Joshua Ashton manually merged in my PR.
I can't seem to be able to reproduce the issue myself in upstream gamescope, tho I had been able to previously (and by previously, I mean before the update to wlroots .18).
But @matte-schwartz said that they still were experience crashing wrt issue #1364 after the upstream gamescope update to wlroots .18, so I'm putting up this PR in case this might fix the rest of the issue
See: 
https://github.com/ValveSoftware/gamescope/issues/1364#issuecomment-2261342586 …
=> wlserver: fix nullptr dereference on oPoint->pTimeline

src/meson.build
looks like gamescope_version needs to apply to the two gamescope color utils following the logging convar in order to fix local builds (CI builds seem fine though)
fixes: https://github.com/ValveSoftware/gamescope/issues/1447
=> build: include missing gamescope_version for color utilities

protocol/meson.build, src/Backends/DRMBackend.cpp, src/Backends/HeadlessBackend.cpp, src/Backends/OpenVRBackend.cpp, src/Backends/SDLBackend.cpp, src/Backends/WaylandBackend.cpp, src/Timeline.cpp, src/Timeline.h, src/Utils/NonCopyable.h, src/WaylandServer/LinuxDrmSyncobj.h, src/WaylandServer/WaylandDecls.h, src/WaylandServer/WaylandProtocol.h, src/WaylandServer/WaylandResource.h, src/WaylandServer/WaylandServerLegacy.h, src/backend.cpp, src/backend.h, src/commit.cpp, src/commit.h, src/gamescope_shared.h, src/meson.build, src/rendervulkan.cpp, src/rendervulkan.hpp, src/steamcompmgr.cpp, src/wlserver.cpp, src/wlserver.hpp
The wlroots protocol is incredibly limiting... In such a way we would need a wlserver lock when we release timeline points, which is totally dumb.
wlroots refcounts not being atomic makes them totally useless for us.
=> Add Wayland protocol C++-y mechanism, and implement linux_drm_syncobj ourselves

src/steamcompmgr.cpp
Software respecting ICCCM will ask for TARGETS first before asking for one of the supported formats. Advertising only STRING will break with any non-ANSI characters, especially since handle_selection_notify() process UTF8 only and gamescope only returns UTF8 strings.
This fixes non-ANSI text copied from Firefox / Chrome running on a Steam deck into any Wine app being a garbled mess.
=> steamcompmgr: Advertise UTF8_STRING in clipboard TARGETS.

src/Backends/DRMBackend.cpp
For BT.709, AMD driver-specific color management properties define the inverse OETF for plane degamma and blend predefined TFs and the OETF for plane shaper and CRTC regamma TFs, as in drm_info:
```
"AMD_PLANE_DEGAMMA_TF": enum {Default, sRGB EOTF, BT.709 inv_OETF, PQ EOTF, Identity, Gamma 2.2 EOTF, Gamma 2.4 EOTF, Gamma 2.6 EOTF}
"AMD_PLANE_SHAPER_TF": enum {Default, Identity, sRGB inv_EOTF, BT.709 OETF, PQ inv_EOTF, Gamma 2.2 inv_EOTF, Gamma 2.4 inv_EOTF, Gamma 2.6 inv_EOTF}
```
By correctly setting degamma and shaper TFs to NV12 planes, we can bring degamma and shaper+3D LUT back and remove the workaround made in [1].
[1] 3b69847e15c8 ("drm: Add workaround for NV12 scanout on SteamOS 3.6")
=> drm: fix wrong degamma/shaper TFs on NV12

src/meson.build
Seems helpful for diagnosing future issues that may come up in one build that may not be present in the same build with a different compiler.
Reports as:
```
❯ gamescope --version
[gamescope] [Info]  console: gamescope version 3.15.5 (clang 18.1.8)
```
for tagged versions but still captures git information properly when between tags or when the tree is dirty
```
❯ gamescope --version
[gamescope] [Info]  console: gamescope version 3.15.0-5-g81d8f8e+ (gcc 14.2.1)
```
could also drop off the compiler version number to keep it cleaner if that's preferable
=> build: add compiler information to gamescope_version

protocol/gamescope-reshade.xml, protocol/meson.build, src/WaylandServer/Reshade.h, src/WaylandServer/WaylandDecls.h, src/reshade_effect_manager.cpp, src/reshade_effect_manager.hpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/wlserver.cpp
Implemented per the suggestion by  @Joshua-Ashton in https://github.com/ValveSoftware/gamescope/issues/1082
=> Add gamescope-reshade Wayland interface

src/meson.build
fixes:
```
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
Configuring GamescopeVersion.h using configuration
```
my bad :frog: easy to miss while doing `meson install -C build/` every time. definitely don't want this eventually failing builds compared to the original behavior.
=> build: fix meson warning for run_command

src/main.cpp, src/steamcompmgr.cpp, src/wlserver.cpp
added a few missing convar descriptions for `gamescopectl help` output. I also chose to align the two HDR related enablement options, `--hdr-enabled` and the revised `--hdr-itm-enabled` so there is no user confusion about the inconsistency in the future. in order not to make this a breaking change for current users, this included adding an additional non-exposed `--hdr-itm-enable` fallback option for legacy usage and adding the same for `--hdr-enable`.  
convar descriptions are based off my understanding of what the convars do through previous conversations, open to suggestions and further clarification there. also let me know if you'd rather leave the hdr convars in their current state and i'll revise this to just include the descriptions.
=> convars, launch options: clean up descriptions and align HDR options

README.md, src/reshade_effect_manager.cpp, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/wlserver.cpp
The current approach crashes when attempting to pass `nullptr` to effect path.
=> Fix how the gamescope-reshade server clears effects

src/Backends/OpenVRBackend.cpp, src/Backends/SDLBackend.cpp, src/Backends/WaylandBackend.cpp, src/backend.h, src/steamcompmgr.cpp
Looks like as part of the backend refactor, copy and paste was partially broken with the SDL backend.  This fixes that broken functionality and lays some groundwork for copy and paste in the wayland backend.
Fixes #1440
=> Add clipboard support from SDL backend

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Open to feedback on these, or let me know if you would prefer simpler markdown templates.
an example implementation is available on my own fork: https://github.com/matte-schwartz/gamescope/issues/new/choose
=> repository: add issue templates

README.md
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
https://mesonbuild.com/Commands.html#setup
> Deprecated since 0.64.0: This is the default Meson command (invoked if there was no COMMAND supplied). However, supplying the command is necessary to avoid clashes with future added commands, so "setup" should be used explicitly.
=> readme: Fix Meson deprecated command warning

.github/workflows/main.yml
https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/
> Following our [change to default customers to use Node20](https://github.blog/changelog/2024-05-17-updated-dates-for-actions-runner-using-node20-instead-of-node16-by-default/), Node16 will reach end of life in the Actions runner on the 15th of October 2024.
> 
> From the 15th of October, we will no longer include Node16 in the Actions runner and customers will no longer be able to use Node16 Actions or operating systems that do not support Node20.
> 
> To prevent disruption to your Actions workflows, if you’re an Actions maintainer, update your actions to run on Node20 instead of Node16. If you’re an Actions user, update your workflows with latest versions of the actions, which run on Node20.
=> update actions/checkout to v4

scripts/00-gamescope/displays/asus.rogally.lcd.lua
This introduces a display configuration for the ROG Ally and ROG Ally X handhelds. These devices feature the same 1920x1080p panel, which supports VRR and has a range limit of 48-120Hz in the EDID.
I tested this configuration on two separate units:
* ROG Ally - SteamOS Main 20240919.1002 with kernel 6.8.12-valve2-1
* ROG Ally X - SteamOS Main 20240919.1002 with kernel 6.11.2
Both function exactly the same throughout multiple games with the entire refresh rate slider within Steam.
=> script: ASUS ROG Ally + ROG Ally X display configuration

scripts/00-gamescope/displays/asus.rogally.lcd.lua, scripts/00-gamescope/displays/deckhd.steamdeck.deckhd-lcd.lua
"value" is not used or defined in either device's lua config for the matches function. Instead, use "display" for the debug output string.
Fixes a coredump when entering gamescope-session on ROG Ally. whoops
=> script: use "display" instead of "value" in debug output

src/main.cpp
This was being set in UpdateCompatEnvVars(), which is called after the environment variable is already read. The default in rendervulkan.cpp if the environment variable isn't set is BT.709 full-range, which is a sane default, so this isn't necessary.
=> Removed GAMESCOPE_NV12_COLORSPACE default

src/rendervulkan.cpp
This was a typo in the formula. The correct formula is as listed on https://en.wikipedia.org/wiki/YCbCr.
Without this change, white comes out as 253,255,255.
=> Fixed conversion from RGB to full range BT.709 YCbCr

src/Backends/DRMBackend.cpp
This serves to attribute the origin of any spurious logging libliftoff would be doing. Otherwise, it simply writes to stderr, and sometimes without any hint that it is coming from libliftoff.
* * *
Hi! :wave: 
Hopefully the change satisfies the coding style. Don't hesitate to discuss changes, or even directly send them here if anything trivial.
I spent some time chasing down *what* printed some log, namely `drmModeAtomicCommit: Permission denied`. Note that this is not aiming to change the conditions where that error would show-up. Though now it is properly attributed to a logging scope. (More on that other log elsewhere, later.)
This also gives a convar (TIL about gamescopectl) to arbitrarily switch the libliftoff log level, which I guess may end-up useful at some point?
Manually, using …
=> DRMBackend: Add libliftoff log handler

src/Backends/WaylandBackend.cpp
This fixes the issue where in a scaled wayland sessions the window buffer is the correct size with window decorations that are too large.
The frame issue effects compositors that don't support server side decoration.
| before | after |
|---|---|
| ![Screenshot From 2024-11-15 22-41-16](https://github.com/user-attachments/assets/8992e0f2-a82a-4968-8f41-1b94d555840e) | ![Screenshot From 2024-11-15 22-41-46](https://github.com/user-attachments/assets/5f42d12e-bd82-40fb-bb61-a5f80fa1e360) |
It also fixes gamescope being having a couple of pixels smaller when fullscreen with 105% scaling.
fixes #1536, fixes #1620
=> WaylandBackend: Fix scale equation and unscale libdecor frame commit

src/Backends/WaylandBackend.cpp
wl_pointer enter/leave events are being processed for libdecor surfaces (they have the tag `libdecor-gtk`), this means the surface user_data is being miscast as CWaylandPlane.
Fixes #1445, fixes #1558, fixes #1434
=> WaylandBackend: Ignore events on unknown surfaces

src/Backends/WaylandBackend.cpp
Per Wayland protocol specsheet regarding keymapping: "From version 7 onwards, the fd must be mapped with MAP_PRIVATE by the recipient, as MAP_SHARED may fail."
https://wayland.app/protocols/wayland#wl_keyboard:event:keymap
This matches up exactly with what we're seeing with this error: `[gamescope] [Error] xdg_backend: Failed to map keymap fd.`
Changing MAP_SHARED to MAP_PRIVATE per the spec addresses this error.
Fixes: #1658
(hopefully) fixes: #1637
=> WaylandBackend: Fix hotkeys failing to bind on Wayland desktops

src/rendervulkan.cpp
After commit https://github.com/ValveSoftware/gamescope/commit/01101093445af20ea25ad386fd872d5f92266c2c running gamescope nested SDL backend on top of x11 plasma causes assertion in wlroots. Related to issue https://github.com/ValveSoftware/gamescope/issues/1218.
```
[gamescope] [Info]  console: gamescope version 3.15.9-10-g6497b0f (gcc 14.2.1)
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
[gamescope] [Info]  vulkan: selecting physical device 'AMD Radeon RX 6800 XT (RADV NAVI21)': queue family 1 (general queue family 0)
[gamescope] [Info]  vulkan: physical device supports DRM format modifiers
[gamescope] [Info]  wlserver: [backend/headless/backend.c:67] Creating headless backend
[gamescope] [Info]  vulkan: supported DRM formats for …
```
=> rendervulkan: Fix getting Vulkan DRM formats if backend doesn't use modifiers

layer/VkLayer_FROG_gamescope_wsi.cpp, protocol/gamescope-swapchain.xml, src/Backends/DRMBackend.cpp, src/Backends/HeadlessBackend.cpp, src/Backends/OpenVRBackend.cpp, src/Backends/SDLBackend.cpp, src/Backends/WaylandBackend.cpp, src/InputEmulation.cpp, src/LibInputHandler.cpp, src/LibInputHandler.h, src/WaylandServer/WaylandServerLegacy.h, src/backend.cpp, src/backend.h, src/main.cpp, src/mangoapp.cpp, src/meson.build, src/messagey.h, src/steamcompmgr.cpp, src/steamcompmgr.hpp, src/steamcompmgr_shared.hpp, src/vblankmanager.cpp, src/wlserver.cpp
WIP, but should be getting there.
Still some to-dos on the side of cursor setting and misc. operations on the WaylandBackend.
=> WIP: Support for multiple virtual connectors

protocol/meson.build, src/Backends/WaylandBackend.cpp, src/steamcompmgr.cpp
This forwards the internal clipboard and primary selection to the host. However,
this does not yet add support for accessing the host's clipboard/selection
internally.
The source for both the clipboard and primary selection are recreated every
time, rather than being reused when they are still valid. Although this doesn't
seem to be necessary, it does appear to be the norm. In particular, the only
difference in behavior I could notice between the two methods is that clipboard
managers are not aware of the new copy when it is reused (this is at least the
case with `wl-paste --watch` under Sway).
This also fixes an issue introduced in d75b122, which broke forwarding selections
to the host altogether, including under the (previously-working) SDL backend.
=> WaylandBackend: clipboard and primary selection support

src/main.cpp
`--adaptive-sync` works regardless of using gamescope embedded or nested, so let's move it to the general args section.
Closes: #1694
`--prefer-output` is a bit vague on how to use it, so let's add an example as suggested.
Closes: #878
=> main: cleanup args

src/steamcompmgr.cpp
This is mandated by the ICCCM specification and Wine now depends on it.
=> steamcompmgr: Set WM_STATE property on map and unmap notify events.

meson.build, src/Script/Script.cpp
This change adds the directory scripts are installed to by `default_scripts_install.sh` to the list of scripts directories in place of the hardcoded `/usr/share/gamescope/scripts`.
For the flatpak the script dir is `/usr/lib/extensions/vulkan/gamescope/share/gamescope/scripts/`
=> scripts: Derive script path from meson prefix

scripts/00-gamescope/displays/lenovo.legiongo.lcd.lua
Add support for the Lenovo Legion Go handheld, which features a rotated 1600x2560 panel that reports 60Hz and 144Hz modes in the EDID. VRR and HDR are not supported, and only one panel model is known to be in use.
Modes other than 60Hz and 144Hz have a small chance of causing a unresponsive touchscreen until another modeset is performed or have artifacts during modesetting, so extra modes are not included. The dynamic_modegen section is filled out in case users decide to add their own refresh rates in a local table.
This configuration has been tested with:
* SteamOS Main 20241025.1000 with kernel 6.8.12-valve3
* Arch Linux with kernel 6.12-rc5
=> script: Lenovo Legion Go display configuration

scripts/00-gamescope/displays/gpd.win4.lcd.lua
This introduces a display configuration for the GPD Win 4 handheld.
Most of this display configuration was derived from the edid as-is, excluding the dynamic_refresh_rates.
All refresh rates were all manually tested with the Steam slider, and the device functioned as expected through multiple games. This was tested on two separate GPD Win 4 devices.
Tested on:
Device DMI  - G1618-04
Distro  - Bazzite 40
Kernels  - 6.9.12-210.fsync.fc40.x86_64 and 6.11.2-201.fsync.fc40.x86_64
All refresh rates were tested with the following games:
- Ghost of Tsushima
- Nier Automata
- Metaphor: ReFantazio (Demo)
- Boomerang Fu
These games were tested with 35hz, 40hz, 50hz, and had no observed issues:
- Crosscode
- Cult of Lamb
- Dave the Diver
- MDA Rain Code Plus
- Shantae and the Seven Sirens
There were …
=> script: GPD Win 4 display configuration

meson.build
OpenVR's CMakelist does not support CMake 4.0 yet, causing build failures in gamescope. Until a new OpenVR SDK is released, let's make sure gamescope stays buildable in the meantime with a workaround which can be removed in the future.
Closes: #1785
=> build: add workaround to build with CMake 4.0

src/rendervulkan.cpp
It already appends VK_STRUCTURE_TYPE_WSI_IMAGE_CREATE_INFO_MESA when creating scanout images to make other Vulkan drivers works, so lets also append VK_STRUCTURE_TYPE_WSI_MEMORY_ALLOCATE_INFO_MESA to make ANV+Xe KMD work.
Closes: https://gitlab.freedesktop.org/mesa/mesa/-/issues/12633
=> rendervulkan: Append VK_STRUCTURE_TYPE_WSI_MEMORY_ALLOCATE_INFO_MESA when creating scanout VkImages

src/Backends/WaylandBackend.cpp
This addresses two related issues around closing windows in the Wayland backend.
1. ~~"Zombie windows":~~ This fix is no longer necessary for me as of 3.16.3.
~~When the last gamescope client closes, the wayland backend tries to
close the window until a new client appears. However, this is done in
the destructor for the connector for the window, which is stored in
a `shared_ptr`. This `shared_ptr` was held by both `steamcompmgr` (which
correctly dropped it) and by the wayland backend, which would never drop
it. This led to the first window being kept around as a "zombie window",
which would show the last frame from the previous client, but otherwise
never update (the backend would only hold a reference to the first
window, and no subsequent ones).~~
~~This fixes this issue by downgrading …
=> WaylandBackend: prevent crash after closing window

scripts/00-gamescope/displays/asus.rogally.lcd.lua
cc @antheas if you want to test this when you get a chance that would be helpful, should work on top of 3.16.3. my TMX panel still matches without any issue but I have no way of verifying on my unit that `data_string` gets populated correctly
=> script: fixup Ally config to support BOE panels

meson.build, src/Script/Script.cpp
Adds `GAMESCOPE_SCRIPT_PATH` as a colon separated list of paths to search for scripts in.
It's also added to the meson devenv which allows developers to test changes by running:
```
meson devenv -C _build
gamescope -- glxgears
```
I'm not sure whether gamescope should exclude all other search paths when `GAMESCOPE_SCRIPT_PATH` is set.
=> scripts: Search GAMESCOPE_SCRIPT_PATH for scripts

src/meson.build
The `dependency()` for stb and glm first searched for system-installed versions, which could an incompatible version (e.g. `stb_image_resize2.h`), it may break the build.
By forcing the use of the subproject wrap files, it will prevent breaking changes due to unpredictable system dependency versions.
=> Force wrap file usage for stb and glm dependencies

scripts/00-gamescope/displays/lenovo.legiongos.lcd.lua
This configuration covers the non-VRR limiter of the Lenovo Legion Go S. In the EDID, only 60Hz and 120Hz are listed as valid modes with different pixel clocks. Because of this, an LCD Deck style for dynamic modegen works best.
The refresh rates within this configuration were tested with hundreds of modesets on my Z2 Go model with a CSW panel.
At this point it's ready for further testing on more units, cc @xinoassassin. for testing the PR, a scripts directory can be made in `~/.config/gamescope/scripts` and then dropping the .lua file into there. once it's merged into gamescope, the local version can be removed.
=> script: Lenovo Legion Go S LCD display configuration

src/wlserver.cpp, src/wlserver.hpp
This ensures that all externally connected keyboards share a common layout and state. If a lock modifier (such as Caps Lock or Num Lock) is enabled or disabled on one keyboard, the state will be propagated to all of them.
If a keyboard is disconnected and then reconnected, the layout and state are preserved.
This behavior is consistent with KWin, which is used in desktop mode.
Fixes: ValveSoftware/steam-for-linux#11529
=> wlserver: Create a keyboard group to keep all externally connected keyboards in sync

src/Backends/WaylandBackend.cpp
Long story short, there are some edge cases where sway may send no_keymap to clients when a virtual keyboard is created on the seat, in specific circumstances. It will later send the xkb keymap before any key events are sent. Other clients simply ignore non-xkb-v1 keymaps (or the lack of a keymap), they don't assert. So gamescope should do the same.
=> WaylandBackend: Don't assert on non-xkb-v1 keymaps

src/main.cpp
This replaces the calls `atoi`/`atof` in `main.cpp` with a function that detects and prints an error when the value being parsed is invalid.
This change has the typical costs and benefits of a tightened specification: new users may get quick feedback that commands like `gamescope --sharpness 1.5` aren't meaningful, but this change could (until someone fixes them) break badly written scripts which invoke gamescope with invalid arguments that happened to work.
=> main: Give error message on invalid integer or float argument

src/wlserver.cpp
During the refactor in 88eb1b477d8b1efbe6d7087dcde74052dad84049, the handle_session_active function lost the ultimate role of *causing a pause* when the session became inactive.
The duty of pausing the session was given the `DirtyState` function on the backend, which now uses the same "moral" condition to set the paused state (`g_DRM.paused = !wlsession_active();`)...
... except that now `DirtyState` state is only called when the session is resumed. In turn, this means that on session suspend, nothing ends-up pausing the DRM backend anymore!
This change unconditionally calls `DirtyState`, which in turn does the accounting for pausing the backend. Actually, it conditionally passes `false` to the argument to force nothing.
This fixes what ends-up causing `drmModeAtomicCommit: Permission …
=> wlserver: Re-hook pausing on session pause

src/Backends/WaylandBackend.cpp
This changed from * 10000 in xx-color-management-v3 to * 1M in color-management-v1.
Fixes `--hdr-itm-enabled --hdr-enabled` after: 1feb11f150e6df0e8325538b7ab28e122bf4b5c9 for non-HDR titles
=> WaylandBackend: fix scaling for TargetPrimaries

subprojects/glm.wrap, subprojects/packagefiles/glm/meson.build
This allows us to correctly override this package for SteamOS builds.
=> build: Pull in glm in the same way we pull in stb

src/steamcompmgr.cpp
Ever since external overlay repaint logic was moved outside of outdatedInteractiveFocus, drawing mangohud on top of the base plane while VRR is enabled can cause the display to jump between different refresh rates. This only seems to happen once a game runs at ~60% or less of the display panel's maximum refresh rate, but it leads to very choppy frame pacing and noticeable VRR flicker.
This choppy VRR effect can actually happen with every type of overlay, including the Steam quick access menus, but mangohud is by far the biggest culprit as it is the only visible overlay that is constantly being drawn on top of the base plane.
This commit adds a workaround to avoid the worst flickering caused by this phenomenon, but the underlying issue will still be present and should be looked into. …
=> steamcompmgr: workaround bug with mangohud repaints and VRR

src/steamcompmgr.cpp
g_bFSRActive was only being applied to the first frame of preemptive upscaling, which meant that the FSR badge would quickly flicker from on to off when preemptive upscaling was active.
To account for this, track the state of preemptive upscaling and use it to activate g_bFSRActive when applicable.
Closes: #1780
=> steamcompmgr: track FSR state with preemptive upscaling

protocol/gamescope-control.xml, src/commit.cpp, src/commit.h, src/steamcompmgr.cpp, src/steamcompmgr_shared.hpp, src/wlserver.cpp, src/wlserver.hpp
A client can now call request_app_performance_stats( app_id ) to query an app's performance details.
=> gamescope-control: add interface to query performance stats for an appid

src/steamcompmgr.cpp
The previous condition (strictly ≠ 0) didn't allow for dropdowns with one of their position hints == 0 to be considered as such.
An instance of this problem could be observed with the account creation screen of Rockstar games where the 'month' dropdown would be displayed correctly (as all 13 entries fitted vertically), but the 'day' and 'year' dropdowns wouldn't be visible because they were taller, and their position ended up with a Y coordinate == 0 (on a screen with a 1280×800 resolution).
=> steamcompmgr: consider windows with 0-position hints valid dropdowns

src/Backends/OpenVRBackend.cpp, src/backend.h, src/steamcompmgr.cpp, src/steamcompmgr_shared.hpp, src/xwayland_ctx.hpp
Implement a system where a window can be tagged with a given VROverlayHandle_t where commit textures will be forwarded to.
These windows are ignored for focus and input is handled out-of-band.
GAMESCOPE_PID is exposed so SetOverlayRenderingPid can be used by the process setting this up to allow Gamescope to set the active texture on the overlay on its behalf.
=> steamcompmgr, openvr: Support forwarding commits to a given VR Overlay

src/Backends/WaylandBackend.cpp
This branch adds a check for `windows_scrgb` support when setting the `bSupportsGamescopeColorManagement` flag.
It also moves unchecked use of the `wp_color_manager_v1` protocol out of the `registry::global` callback so that the compositor has an opportunity to send information on what features are supported during the subsequent roundtrip.
This fixes a wayland protocol error and allows gamescope on gnome/mutter.
~This avoids using windows_scrgb where unsupported. `m_pWPImageDescriptions[ GAMESCOPE_APP_TEXTURE_COLORSPACE_SCRGB ]` won't be set if the feature isn't reported. It should still crash in `CWaylandPlane::Present` if switching to `GAMESCOPE_APP_TEXTURE_COLORSPACE_SCRGB`, however now it logs an error explaining why.~
~The color-management-v1 protocol says that surfaces without a …
=> WaylandBackend: Check features before using color management

src/backend.h, src/rendervulkan.cpp
The invalid modifier is not supported under vulkan, so fall back to any other modifier if a format does not support the invalid modifier.
Closes #1604
=> WaylandBackend: allow gamescope to run under vulkan

.editorconfig
The codebase has lots of inconsistent indentation between 1 tab or 4
spaces. Rather than having massive diffs by fixing all that, this sets
the editorconfig tab width to 4, so it's at least visually consistent,
even on editors that default to 8-wide tabs.
=> Consistent indentation

README.md
Applies `?exclude_unsupported=1` to the Repology view. 
There is no reason to show, for example, 6 dead versions of Fedora (from a total of 9).
Before             |  After
:-------------------------:|:-------------------------:
=> README.md: Exclude end of life distributions in Repology status
