- meson.build
Depends on https://github.com/Plagman/wlroots/pull/2
> Build wlroots as a static subproject

- README.md
> Correct integer scaling example in README

- .gitmodules
- src/wlserver.c
- src/wlserver.h
Use wlr_xwayland_server, which allows enough customization for us.
References: https://github.com/swaywm/wlroots/pull/2175
Closes: https://github.com/Plagman/gamescope/issues/15
> Use upstream wlr_xwayland_server

- src/steamcompmgr.cpp
Closes: https://github.com/Plagman/gamescope/issues/79
> Set WM_STATE and NET_WM_STATE

- src/main.cpp
- src/main.hpp
- src/sdlwindow.cpp
- src/steamcompmgr.cpp
Allows to pass '-f' to start gamescope in fullscreen if nested.
> Add an option to start in fullscreen if nested

- src/composite.comp.hlsl
- src/drm.cpp
- src/rendervulkan.cpp
- src/rendervulkan.hpp
- src/steamcompmgr.cpp
Eliminates these comparisons being done from the constant buffer.
> Move nLayerCount and bSwapLayers to spec constants

- src/rendervulkan.cpp
Tested with radv + radeonsi + glxgears on navi21 to work with DCC (assuming
the nodcc bit is disabled).
This is conservative and will fall back to the legacy path if the modifier
isn't supported. At the same time it also avoids the wird mesa WSI struct
if the modifier is supported.
radv MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8817
Up to you when/whether to remove the nodcc bits.
> Support Vulkan modifier-based imports using VK_EXT_image_drm_format_modifier

- meson.build
- src/steamcompmgr.cpp
References: https://github.com/Plagman/gamescope/issues/17
> Query window PID via XRes

- src/steamcompmgr.cpp
Supersedes https://github.com/Plagman/gamescope/pull/173
> Fix is_focus_priority_greater function

- src/rendervulkan.cpp
This allows us to remove the wsi_image_create_info hack when
modifiers are supported.
References: https://github.com/Plagman/gamescope/issues/51
cc @BNieuwenhuizen
> Pass list of modifiers when allocating with Vulkan

- src/steamcompmgr.cpp
Ref https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.4
> steamcompmgr: handle WM_CHANGE_STATE messages

- src/drm.cpp
Currently fails with
```
[98984.145368] [drm:drm_atomic_check_only [drm]] [CRTC:70:crtc-1] requesting event but off
[98984.145398] [drm:drm_atomic_check_only [drm]] [CRTC:70:crtc-1] atomic core check failed
```
> drm: atomically disable CRTCs

- .gitmodules
- src/main.cpp
- src/steamcompmgr.cpp
- src/steamcompmgr.hpp
>  Add --cursor argument to load a custom cursor

- src/main.cpp
- src/rendervulkan.cpp
- src/rendervulkan.hpp
Otherwise all our modifiers/formats and stuff are garbage.
Fixes: #269
> Init format info after initializing DRM

- src/rendervulkan.cpp
RADV does retiling in that barrier. Still hinky overall but this fixes
using compositing with DCC compressed images on RADV.
> Add a proper release barrier for modifier based images when not nested.

- src/composite.comp
- src/rendervulkan.cpp
I missed adding this back in when I did the PR that was meant to fix this when I was debugging... Oops.
> rendervulkan: Sample at texel centers

- src/drm.cpp
- src/drm.hpp
- src/rendervulkan.cpp
- src/rendervulkan.hpp
- src/steamcompmgr.cpp
To avoid the SDMA work on Vulkan import/close.
> Memoize imported vulkan textures / drm framebuffers

- src/main.cpp
- src/steamcompmgr.cpp
- src/steamcompmgr.hpp
Allow setting the hotspot for the custom cursor.
> steamcompmgr: Add --cursor-hotspot

- src/drm.cpp
- src/drm.hpp
- src/rendervulkan.cpp
- src/rendervulkan.hpp
- src/steamcompmgr.cpp
- src/steamcompmgr.hpp
Seems to have worked out those phantom bugs we have during video streaming.
> Simplify ref-counting a lot

- src/steamcompmgr.cpp
Fixes seamless boot again on valve9
> steamcompmgr: Fix returning valid contents

- src/rendervulkan.cpp
This was already commented out when it was added 2 years ago, and it doesn't
seem useful. But maybe I'm missing something.
> rendervulkan: Remove dead fence code.

- src/steamcompmgr.cpp
Fixes Origin windows being in funny places when fading.
> steamcompmgr: Update last done commit on focus change

- meson.build
- src/main.cpp
- src/main.hpp
- src/steamcompmgr.cpp
- src/steamcompmgr.hpp
- src/wlserver.cpp
- src/wlserver.hpp
- src/xwayland_ctx.hpp
Allows us to virtualize focus from the game so it never knows we're doing something different.
Closes: https://github.com/Plagman/gamescope/issues/328
> Support for multiple xwaylands and focus/painting across them

- src/steamcompmgr.cpp
If we dirty the X server outside of the dispatch, xlib can flush its events, leading us to a state where XPending(dpy), would be true but the poll returns false.
Check if we have locally queued events before polling and flush those to mitigate this. This does not involve a system call.
> steamcompmgr: Track X dirtying outside of dispatch

- src/steamcompmgr.cpp
- src/xwayland_ctx.hpp
Avoids bubbles of no focus window
> steamcompmgr: Keep being interactive when switching between focus windows and waiting for commits

- src/rendervulkan.cpp
- src/steamcompmgr.cpp
> Fix a few cursor bugs!

- meson.build
- src/main.cpp
- src/main.hpp
- src/rendervulkan.cpp
- src/rendervulkan.hpp
- src/sdlwindow.cpp
- src/shaders/composite.h
- src/shaders/cs_composite_blit.comp
- src/shaders/cs_composite_rcas.comp
- src/shaders/cs_easu.comp
- src/shaders/cs_easu_fp16.comp
- src/shaders/descriptor_set.h
- src/shaders/ffx_a.h
- src/shaders/ffx_fsr1.h
- src/steamcompmgr.cpp
-U or Super + U to enable FSR for layer 0.
Might be better to disable fp16 until https://gitlab.freedesktop.org/mesa/mesa/-/issues/5002 is resolved.
> FSR support.

- src/steamcompmgr.cpp
- src/steamcompmgr.hpp
- src/wlserver.cpp
Raise them and simplify all the cursor and focus logic here.
Handle them being off screen, size accordingly
> Rework override redirects a bit

- src/mangoapp.cpp
Adding variables to the mangoapp message queue to be able to show gamescope FSR status and sharpness level
> mangoapp: FSR

- src/steamcompmgr.cpp
Prefers dropdowns over popups.
> steamcompmgr: Prefer non-dialog override redirects

- src/steamcompmgr.cpp
With matching stuff in mesa to dynamically change the swapchain
to FIFO (or the approximate GL equivalent).
Needs `GAMESCOPE_LIMITER_FILE` set to do anything.
> Add support for communicating a swapchain override to apps.

- src/drm.cpp
- src/drm.hpp
- src/pipewire.cpp
- src/rendervulkan.cpp
- src/rendervulkan.hpp
- src/steamcompmgr.cpp
- src/steamcompmgr.hpp
Simple patches from my bigger renderer rework.
> Minor preparation cleanup. 

- src/main.cpp
- src/main.hpp
- src/steamcompmgr.cpp
> Add realtime flag for SCHED_RR

- src/drm.cpp
- src/drm.hpp
Use a more human-readable string.
> drm: improve wl_output.description

- meson.build
- src/drm.cpp
- src/rendervulkan.hpp
Implements the new unset prop from libliftoff
> drm: Unset COLOR_RANGE and COLOR_ENCODING if not YCbCr or unbound

- src/drm.cpp
Works around test commits taking way too long.
Still something that should be fixed for sure, but probably better to avoid the churn anyway.
> drm: Cache composition results from liftoff

- src/wlserver.cpp
- src/wlserver.hpp
Closes: https://github.com/Plagman/gamescope/issues/571
> wlserver: create one wl_output global per Xwayland server

- src/wlserver.cpp
The inverse case of the pending surfaces...
> wlserver: Handle wl commits before X11 surface has come up

- src/drm.cpp
- src/wlserver.cpp
- src/wlserver.hpp
Not very pretty, but can help with badly behaved clients…
> Stop recreate output global

- src/drm.cpp
- src/drm.hpp
- src/wlserver.cpp
This pulls the information from the KMS to determine when or if to rotate the display.
> Add the orientation-quirk props logic

- src/rendervulkan.cpp
Regressions from f072cbd58b0ab373f486bf1647b7acd0ffce8f0d.
> rendervulkan: Fix some validation errors.

- src/rendervulkan.cpp
How did I not see this before :frog:.
> rendervulkan: Fix a typo

- meson.build
- src/ime.cpp
- src/wlserver.cpp
- src/wlserver.hpp
Closes: https://github.com/Plagman/gamescope/issues/667
> wlserver, ime: Port to wlroots 0.16.0

- src/wlserver.cpp
Fixes #690
Unsure if this is the right way to fix it
> wlserver: fix pointer scroll in nested mode

- .gitmodules
- layer/VkLayer_FROG_gamescope_wsi.cpp
- layer/VkLayer_FROG_gamescope_wsi.json
- layer/meson.build
- meson.build
- protocol/meson.build
- src/drm.cpp
- src/drm.hpp
- src/steamcompmgr.cpp
- src/steamcompmgr.hpp
- src/wlserver.cpp
- src/wlserver.hpp
- src/xwayland_ctx.hpp
Initial work on a layer to bypass Xwayland. Definitely not complete and definitely doesn't handle any edgecases with windows (as of this PR anyway. I have a bunch of work to swap out surfaces and make the swapchain out of date that isn't here in the initial stuff yet) .
> layer: Add gamescope_wsi layer 

- src/shaders/colorimetry.h
> shaders: avoid division by zero for BT.2446 Method A itm

- src/steamcompmgr.cpp
> steamcompmgr: Fix typo in comment

- src/drm.cpp
Use a fallback mode size and refresh rate, to avoid surprising our clients too much and allow screen recording to continue working.
Closes #703
> drm: add support for headless setup

- src/meson.build
> build: update libdisplay-info pkgconfig filename

- .github/workflows/main.yml
- meson.build
- src/color_bench.cpp
- src/color_helpers.cpp
- src/color_helpers.h
- src/drm.cpp
- src/meson.build
- src/rendervulkan.hpp
- src/steamcompmgr.cpp
Gets generating the 1D + 3D LUTs down from ~4ms -> 1.5ms.
> Selection of color mgmt optimizations

- meson.build
- src/meson.build
Fixes build after 5151250d9433f978429cf7572b5159394c082355 for me.
> main: Add "wayland-client" dependency

- src/drm.cpp
> drm: fix other headless NPE

- README.md
This shortcut was removed in 371fcf0.
> readme: Remove dead shortcut

- src/main.cpp
- src/main.hpp
- src/sdlwindow.cpp
This is a no-op in windowed mode, but it works as expected in fullscreen mode :D
> Support to put nested window on a certain display

- meson.build
> Only use system OpenVR if it's at least version 2

- src/sdlwindow.cpp
<p align=center><img src="https://github.com/ValveSoftware/gamescope/assets/44510779/7f20c01d-cb17-4747-9174-4b7531f0b050"><p align=center>↓<p align=center><img src="https://github.com/ValveSoftware/gamescope/assets/44510779/65c81ded-b1f0-4b59-a75d-d9314a72561e">
> sdlwindow: Display app name and title for screen saver

- src/drm.cpp
Allows gamescope to start on currently released Nvidia drivers
> drm: Check DRM_SYNC_OBJ_CAP and hook up SupportsExplicitSync()

- src/meson.build
Updates libliftoff to fix compile error on GCC 14
> Fix GCC14 build

- src/steamcompmgr.cpp
Closes https://github.com/ValveSoftware/gamescope/issues/1311
second time's the charm 🐸
> steamcompmgr: Remove unnecessary abort function

- src/drm.cpp
> Avoid Libliftoff timeout

- src/drm.cpp
The NVIDIA DRM driver doesn't support IN_FENCE_FD
yet, but it has no way to indicate this to
userspace. When a commit fails with -EPERM, try
setting IN_FENCE_FD to -1 and retrying it. If this succeeds, disable use of IN_FENCE_FD from then on.
> Disable use of IN_FENCE_FD if it fails

- layer/VkLayer_FROG_gamescope_wsi.cpp
- protocol/gamescope-swapchain.xml
- src/WaylandServer/WaylandServerLegacy.h
- src/mangoapp.cpp
- src/steamcompmgr.cpp
- src/steamcompmgr.hpp
- src/steamcompmgr_shared.hpp
- src/wlserver.cpp
Same as #1653 but for this different branch
> mangoapp: plumb engineName

- src/Backends/WaylandBackend.cpp
This stops gamescope from overriding libdecor cursors for resizing the frame.
This may need further testing. It may be a good idea to ignore events that don't have a surface parameter based on `m_bMouseEntered`.
| before | after |
|-|-|
| ![Screencast From 2024-12-06 20-45-38.webm](https://github.com/user-attachments/assets/de8c7304-7c27-428a-b693-510cd72539dd) | ![Screencast From 2024-12-06 20-46-13.webm](https://github.com/user-attachments/assets/def1785d-a0e6-4946-9148-e9460b6be5de) |
> WaylandBackend: Filter more libdecor surfaces

- src/Backends/WaylandBackend.cpp
> WaylandBackend: Fix IsPaused return value
